### PR TITLE
fix: incorrect workspace folder path

### PR DESCRIPTION
**Pull request by dulingzhi**
#28

### CODE REVIEW

**Comment by dulingzhi** [comment]
Hi @Koihik can you release a new version? 
This bug causes the plugin to not work properly.

**Comment by Koihik** [comment]
@dulingzhi v1.3.5 that contains this PR has been released 2 weeks ago. Maybe this problem has not been completely fixed.

**Comment by dulingzhi** [comment]
image

No, 1.3.5 not contains this PR.
The screenshot shows the code for 1.3.5.

**Comment by Koihik** [comment]
@dulingzhi Released v1.3.6

**Pull request merged**
